### ISSUE TITLE
About the demo of attacking N2NMN

### ISSUE THREAD

**Issue by hhhzzj** [akshay107/mimic-and-fool#1]
Hi, when i ran `prepare_target.py` followed by `main.py` according to the `README.md`. However, I got some problem. First, when i ran `main.py`, I got an issue from`targets = np.load("/home/cvpr/akshay/resnet_res5c/"+fname)`  and i annotated it and got the following issue:

Traceback (most recent call last):
  File "main.py", line 94, in <module>
    new_model.load_weights('init_weights.h5')
  File "/home/huangzijie/anaconda3/lib/python3.6/site-packages/keras/engine/network.py", line 1157, in load_weights
    with h5py.File(filepath, mode='r') as f:
  File "/home/huangzijie/anaconda3/lib/python3.6/site-packages/h5py/_hl/files.py", line 408, in __init__
    swmr=swmr)
  File "/home/huangzijie/anaconda3/lib/python3.6/site-packages/h5py/_hl/files.py", line 173, in make_fid
    fid = h5f.open(name, flags, fapl=fapl)
  File "h5py/_objects.pyx", line 54, in h5py._objects.with_phil.wrapper
  File "h5py/_objects.pyx", line 55, in h5py._objects.with_phil.wrapper
  File "h5py/h5f.pyx", line 88, in h5py.h5f.open
OSError: Unable to open file (unable to open file: name = 'init_weights.h5', errno = 2, error message = 'No such file or directory', flags = 0, o_flags = 0)

Could you please help me to fix it? Thank you so much!!!

**Comment by akshay107** [comment]
Hi, thanks for pointing out the issue. Those two lines (targets = np.load("/home/cvpr/akshay/resnet_res5c/"+fname) and new_model.load_weights('init_weights.h5')) are not needed. I have removed those two lines. I have also made few other minor changes.
